version: 2.1

jobs:
  build:
    docker:
      - image: sceptreorg/sceptre-circleci:2.0.0

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: poetry install -v

      - save_cache:
          key:
            v1-dependency-cache-{{ checksum "pyproject.toml" }}-{{ checksum "poetry.lock" }}
          paths:
            - '~/.cache/pypoetry'

      - run:
          name: Run pre-commit
          command: poetry run pre-commit run --all-files

      - run:
          name: Build package
          command: poetry build

  tests:
    docker:
      - image: sceptreorg/sceptre-circleci:2.0.0

    steps:
      - checkout

      - restore_cache:
          key:
            v1-dependency-cache-{{ checksum "pyproject.toml" }}-{{ checksum "poetry.lock" }}

      - run:
          name: Unit Tests
          command: poetry run tox

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: htmlcov
          destination: coverage-reports

  deploy-test:
    docker:
      - image: sceptreorg/sceptre-circleci:2.0.0

    steps:
      - checkout

      - restore_cache:
          key:
            v1-dependency-cache-{{ checksum "pyproject.toml" }}-{{ checksum "poetry.lock" }}

      - run:
          name: Test upload to PyPi
          command: |
            poetry config repositories.test-pypi "https://test.pypi.org/legacy/"
            poetry publish --build -r test-pypi -u $PYPI_TEST_USER -p $PYPI_TEST_PASSWORD

  deploy-prod:
    docker:
      - image: sceptreorg/sceptre-circleci:2.0.0

    steps:
      - checkout

      - restore_cache:
          key:
            v1-dependency-cache-{{ checksum "pyproject.toml" }}-{{ checksum "poetry.lock" }}

      - run:
          name: Upload to PyPi
          command: poetry publish --build -u $PYPI_PROD_USER -p $PYPI_PROD_PASSWORD

workflows:
  test:
    jobs:
      - build
      - tests:
          requires:
            - build
  tag:
    jobs:
      - deploy-test:
          context: sceptre-templates-context
          filters:
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
            branches:
              ignore: /.*/
      - deploy-prod:
          context: sceptre-templates-context
          requires:
            - deploy-test
          filters:
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
            branches:
              ignore: /.*/
